Check missing dependencies

diff --git a/portable2appimage b/portable2appimage
--- a/portable2appimage
+++ b/portable2appimage
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-P2AVER="1.0.6"
+P2AVER="1.0.7"
 
 FILE="$1"
 
@@ -38,11 +38,50 @@ cd "$APP"-workdir.tmp || exit 1
 # Check if FILE is an archive
 ################################################
 
-if test -e ./*7z; then 7z x ./*7z 2>/dev/null && rm -f ./*7z; fi
-if test -e ./*.deb; then ar x ./*.deb && rm -f ./*.deb && tar fx ./data.tar* && rm -f ./*tar.*; fi
-if test -e ./*tar.*; then tar fx ./*tar.* && rm -f ./*tar.*; fi
-if test -e ./*tbz; then tar fx ./*tbz && rm -f ./*tbz; fi
-if test -e ./*zip; then unzip -qq ./*zip 1>/dev/null && rm -f ./*zip; fi
+if test -e ./*7z; then
+	if command -v 7z 1>/dev/null; then
+		7z x ./*7z 2>/dev/null && rm -f ./*7z
+	else
+		echo "Missing command: 7z" && exit 1
+	fi
+fi
+
+if test -e ./*.deb; then
+	if command -v ar 1>/dev/null; then
+		ar x ./*.deb && rm -f ./*.deb
+		if command -v tar 1>/dev/null; then
+			tar fx ./data.tar* && rm -f ./*tar.*
+		else
+			echo "Missing command: tar" && exit 1
+		fi
+	else
+		echo "Missing command: ar (provided by \"binutils\")" && exit 1
+	fi
+fi
+
+if test -e ./*tar.*; then
+	if command -v tar 1>/dev/null; then
+		tar fx ./*tar.* && rm -f ./*tar.*
+	else
+		echo "Missing command: tar" && exit 1
+	fi
+fi
+
+if test -e ./*tbz; then
+	if command -v tar 1>/dev/null; then
+		tar fx ./*tbz && rm -f ./*tbz
+	else
+		echo "Missing command: tar" && exit 1
+	fi
+fi
+
+if test -e ./*zip; then
+	if command -v unzip 1>/dev/null; then
+		unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
+	else
+		echo "Missing command: unzip" && exit 1
+	fi
+fi
 
 mv ./* ../"$APPDIR"/ && mv ../"$APPDIR" ./ && cd "$APPDIR" || exit 1
 
@@ -124,6 +163,13 @@ else
 	Categories=Utility;
 	HEREDOC
 fi
+
+if ! command -v desktop-file-validate 1>/dev/null; then
+	echo "desktop-file-validate: command not found!"
+	echo "Install the \"desktop-file-utils\" package and retry."
+	exit 1
+fi
+
 while ! desktop-file-validate ./*.desktop 2>/dev/null; do
 	echo "Fixing issues..."
 
